ALTER TABLE sentitrack_products ADD COLUMN scent_category VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN';
UPDATE sentitrack_products SET scent_category = 'WOODY' WHERE id = 1;
UPDATE sentitrack_products SET scent_category = 'FLORAL' WHERE id = 2;
UPDATE sentitrack_products SET scent_category = 'AQUATIC' WHERE id = 3;
UPDATE sentitrack_products SET scent_category = 'ORIENTAL' WHERE id = 4;
UPDATE sentitrack_products SET scent_category = 'WOODY' WHERE id = 5;
UPDATE sentitrack_products SET scent_category = 'MUSKY' WHERE id = 6;
UPDATE sentitrack_products SET scent_category = 'GREEN' WHERE id = 7;
UPDATE sentitrack_products SET scent_category = 'AQUATIC' WHERE id = 8;
UPDATE sentitrack_products SET scent_category = 'FLORAL' WHERE id = 9;
UPDATE sentitrack_products SET scent_category = 'FRESH' WHERE id = 10;
